let pencilPrice = 10;
let erasorPrice = 5;
console.log("The total price is :",pencilPrice + erasorPrice,"Rupees.");
let output = "The total price is : "+pencilPrice + erasorPrice+" Rupees.";
console.log(output);
output = "The total price is : "+(pencilPrice + erasorPrice)+" Rupees.";
console.log(output);
output = `The total price is : ${pencilPrice + erasorPrice} Rupees.`;
console.log(output);
console.log(`The total price is : ${+pencilPrice + erasorPrice} Rupees.`);
console.log("Total:", 15);